### ISSUE TITLE
Add collaborator

### ISSUE THREAD

**Issue by ingbrzy** [sazuke0703/Miui8-Thai-Language#2]
Please add @MarkH-UK as collaborator... thanks

**Comment by ingbrzy** [comment]
Please add @MarkH-UK as collaborator... thanks

**Comment by ingbrzy** [comment]
Please add @MarkH-UK as collaborator... thanks

**Comment by ingbrzy** [comment]
is this repo still alive? I see no changes since July...

**Comment by ingbrzy** [comment]
Your issues will be fixed if you add him 
http://translators.xiaomi.eu/XML_MIUI8-Thai-th.html

**Comment by ingbrzy** [comment]
@sazuke0703

**Comment by sazuke0703** [comment]
OK , I have a problem with the phone
Now I have time to add them.

**Comment by sazuke0703** [comment]
https://github.com/sazuke0703/Miui8-Thai-Language/settings/collaboration

**Comment by sazuke0703** [comment]
Why i cannot creat folder on github.

**Comment by sazuke0703** [comment]
I want to add extras and add some translate.

**Comment by sazuke0703** [comment]
I cannot creat folder  it show  " This file is hidden".

**Comment by ingbrzy** [comment]
added... https://github.com/sazuke0703/Miui8-Thai-Language/commit/2e204b27849049017609363fc3de451441596b72
